export const pocConfig = {
  autoCollapseDisabled: false,
  collapsedBreakpoint: 'md',
  secondaryAutoCollapseDisabled: false,
  secondaryCollapseBreakpoint: 'md',
  heightAdjustmentDisabled: false,
  insetHiddenBreakpoint: 'sm',
  insetHiddenDisabled: false,
  secondaryInsetHiddenBreakpoint: 'md',
  secondaryInsetHiddenDisabled: false,
  xs: {
    sidebar: {
      anchor: 'left',
      variant: 'temporary',
      width: 256,
      collapsible: false,
      collapsedWidth: 64,
      hidden: false,
      inset: false,
      insetProps: {
        position: 'fixed',
      },
    },
    secondarySidebar: {
      anchor: 'right',
      variant: 'persistent',
      width: 244,
      collapsible: true,
      collapsedWidth: 64,
      hidden: false,
      inset: false,
      insetProps: {
        position: 'sticky',
      },
    },
    header: {
      offsetHeight: 64,
      position: 'sticky',
      clipped: false,
      secondaryClipped: false,
      persistentBehavior: 'fit',
      secondaryPersistentBehavior: 'fit',
    },
    content: {
      persistentBehavior: 'flexible',
      secondaryPersistentBehavior: 'none',
    },
    footer: {
      persistentBehavior: 'fit',
      secondaryPersistentBehavior: 'none',
      insetBehavior: 'fit',
      secondaryInsetBehavior: 'none',
    },
  },
  md: {
    sidebar: {
      anchor: 'left',
      variant: 'permanent',
      width: 200,
      collapsible: false,
      collapsedWidth: 64,
      hidden: false,
      inset: false,
      insetProps: {
        position: 'fixed',
      },
    },
    secondarySidebar: {
      anchor: 'right',
      variant: 'persistent',
      width: 244,
      collapsible: true,
      collapsedWidth: 64,
      hidden: false,
      inset: false,
      insetProps: {
        position: 'sticky',
      },
    },
    header: {
      position: 'sticky',
      offsetHeight: 64,
      clipped: true,
      secondaryClipped: false,
      persistentBehavior: 'fit',
      secondaryPersistentBehavior: 'fit',
    },
    content: {
      persistentBehavior: 'flexible',
      secondaryPersistentBehavior: 'none',
    },
    footer: {
      persistentBehavior: 'fit',
      secondaryPersistentBehavior: 'none',
      insetBehavior: 'fit',
      secondaryInsetBehavior: 'none',
    },
  },
  lg: {
    sidebar: {
      anchor: 'left',
      variant: 'permanent',
      width: 256,
      collapsible: false,
      collapsedWidth: 64,
      hidden: false,
      inset: false,
      insetProps: {
        position: 'fixed',
      },
    },
    secondarySidebar: {
      anchor: 'right',
      variant: 'persistent',
      width: 244,
      collapsible: true,
      collapsedWidth: 64,
      hidden: false,
      inset: false,
      insetProps: {
        position: 'sticky',
      },
    },
    header: {
      position: 'sticky',
      offsetHeight: 64,
      clipped: true,
      secondaryClipped: false,
      persistentBehavior: 'fit',
      secondaryPersistentBehavior: 'fit',
    },
    content: {
      persistentBehavior: 'flexible',
      secondaryPersistentBehavior: 'none',
    },
    footer: {
      persistentBehavior: 'fit',
      secondaryPersistentBehavior: 'none',
      insetBehavior: 'fit',
      secondaryInsetBehavior: 'none',
    },
  },
}